apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app
  namespace: prod
  labels:
    app: prod-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: prod-app
        image: ${IMGPATH}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ocir
      

---

apiVersion: v1
kind: Service
metadata:
  name: svc-prod-app
  namespace: prod
spec:
  selector:
    app: prod-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer